
PUT http://localhost:8080/user/38209948822 HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiODE5NTlhLWI0MjMtNGMwOC04NGUwLTFjNjM2ODgyMTBmZCIsIm5hbWUiOiJHYWJyaWVsIiwiY3BmIjoiMzgyMDk5NDg4MjIiLCJwYXNzd29yZCI6IiQyYiQxMCRvTktKclhVSUpLVzliNUxWNFdHMi5lNTBWakFxS3poZXpsYUZ6MG8uSktZVm9RcDBFcncubSIsIm1hbmFnZXIiOnRydWUsImJhbGFuY2UiOiIwLjAwIiwiY2xpZW50QmFsYW5jZSI6IjAuMDAiLCJwYXJlbnRBY2NvdW50IjpudWxsLCJjaGlsZEFjY291bnRzIjpbXSwiaWF0IjoxNzMwMTU5MjI5LCJleHAiOjE3MzAxNjI4Mjl9.6YtrCa6cdIFIYnqI-rECeWLeo6W7q0INH0fwEbUUrdE

{
    "name": "Gabriel"
}