
GET http://localhost:8080/user/01111111111 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5YzExY2NmLTA0ZmEtNDZiZS1hN2RlLTQ1MTk5ZDZhMWU0MSIsIm5hbWUiOiJHYWJyaWVsIiwiY3BmIjoiMDExMTExMTExMTEiLCJwYXNzd29yZCI6IiQyYiQxMCRJYmRYMjZuZ0xOcy52M0JTaFlIODBlUENvNmdHRVpaZmw0UHE0emZVYmJIdS80aTNrMkVKeSIsInJvbGUiOiJhZG1pbiIsImFjdGl2ZSI6dHJ1ZSwiYWNjZXNzRXhwaXJhdGlvbiI6IjIwMjQtMTEtMTVUMTg6MTQ6MDkuMzc3WiIsImlhdCI6MTczMTUyMTY0OSwiZXhwIjoxNzMxNTI1MjQ5fQ.nbdgVpv1G31ldBICEWluzi65_yrxdlnDl7EOzM3uUlw
