
GET http://localhost:8080/file HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5YzExY2NmLTA0ZmEtNDZiZS1hN2RlLTQ1MTk5ZDZhMWU0MSIsIm5hbWUiOiJHYWJyaWVsIiwiY3BmIjoiMDExMTExMTExMTEiLCJwYXNzd29yZCI6IiQyYiQxMCRJYmRYMjZuZ0xOcy52M0JTaFlIODBlUENvNmdHRVpaZmw0UHE0emZVYmJIdS80aTNrMkVKeSIsInJvbGUiOiJhZG1pbiIsImFjdGl2ZSI6dHJ1ZSwiYWNjZXNzRXhwaXJhdGlvbiI6IjIwMjQtMTEtMTZUMDM6NDk6NTAuNTMxWiIsImlhdCI6MTczMTU1NjE5MCwiZXhwIjoxNzMxNTU5NzkwfQ.WzUfxmDJ8X77BZx8ltFRYEnD-_tuw8GbjfotKyCmorE
